### ISSUE TITLE
Growth Parameters

### ISSUE THREAD

**Issue by paviaishu16** [paviaishu16/Multiplate-reader-data-analyser#20]
- [ ] 1. Top 10 Growth Rate:
Identify the top 10 slope values from each column (the values should be greater than zero) 

- [ ] 2. Time point of the corresponding slope value (T):
For the above slope values find the corresponding time point

- [ ] 3. Lag Time (L):
From step 2, identify the lowest time point but more than 13 hours

- [ ] 4. Maximum Growth Rate (k):
Identify the maximum growth rate value from Task 1 (where the time point is between 20 and 48 hours)

- [ ] 5. Inflection point (t):
The time point corresponding to (k)

- [ ] 6. Asymptotic Maximum Population (A):
Identify the highest value from the table obtained after the data cleanup before finding slope

**Comment by gevhaz** [comment]
Is my understanding correct that:

- `A` comes from the blanked and renormalized data, not from the slope data.
- All other values should be calculated per column. So each column has its own `t`, `k`, and `L`.

**Comment by paviaishu16** [comment]
Yes, that's right!

**Comment by paviaishu16** [comment]
As an outcome of all the tasks above there will be two excel files:
1. Top 10 growth rate values and the corresponding T values
2. `L`, k, t, A,

**Comment by gevhaz** [comment]
Moving construction of DataFrame (1) to #23 and creation of Excel sheets to #24.

**Comment by gevhaz** [comment]
Do these growth parameters look reasonable @paviaishu16?

```
       L         k     t         A
A1  44.5  0.334637  29.5  1.606992
A2  68.0  0.629773  21.5  1.343997
A3  52.5  0.331019  28.5  1.546246
A4  70.0  0.433950  35.0  1.458670
A5  49.0  0.398861  23.5  1.341517
A6  66.5  0.421440  21.5  1.604071
A7  62.0  0.460135  46.0  1.518865
A8  64.0  0.356622  42.5  1.199619
```
