### ISSUE TITLE
Gompertz and Richards analysis

### ISSUE THREAD

**Issue by paviaishu16** [paviaishu16/Multiplate-reader-data-analyser#27]
https://chatgpt.com/share/670cec43-8f88-8011-9355-500688b5cbb9

Take a look at this

**Comment by paviaishu16** [comment]
N0 * np.exp(np.log(N_inf / N0) * (1 - np.exp(-alpha * t)))

- N0 is the first row value from the data cleanup before finding slope
- N inf is the A value
- alpha is the growth rate k

We initially create a gompertz model using the growth parameters that we have obtained and using that here. Say for example:
N0 is 0.0425
N inf is 4.562
k is 0,19

Then the gompertz model for A1 would go as below:
Time | A1
0.5    | 0.0425 * np.exp(np.log(4.562 / 0.0425) * (1 - np.exp(-0,19 *0.5)))
1       | 0.0425 * np.exp(np.log(4.562 / 0.0425) * (1 - np.exp(-0,19 *1)))
1.5    | 0.0425 * np.exp(np.log(4.562 / 0.0425) * (1 - np.exp(-0,19 *1.5)))
2      | 0.0425 * np.exp(np.log(4.562 / 0.0425) * (1 - np.exp(-0,19 *2)))
2.5    | 0.0425 * np.exp(np.log(4.562 / 0.0425) * (1 - np.exp(-0,19 *2.5)))


So this becomes the **Predicted model**

Then we do the curve fitting (Point 5 in chatgpt convo), where the python tool evaluates the growth parameters and generates new parameters that fits the best for this data. 

The term **noisy data** in the chatgpt convo refers to the data obtained after the cleanup

**Comment by paviaishu16** [comment]
Richards formula:
def richards_growth_with_A0(t, A, K, t0, A0, nu):
    Q = ((A / A0) ** nu) - 1
    return A * (1 + Q * np.exp(-K * (t - t0))) ** (-1 / nu)
t0 is the time at which the slope or growth is maximum
nu = 1,5

**Comment by gevhaz** [comment]
Could you review this help text?

```python
def richards_model(t, A, k, t0, A0, nu=1.5):
    """Get population given time and parameters using Richard's model.

    Args:
        t: Timepoint or Series of timepoints for which to determine
           the population.
        A: Asymptotic max population. The highest value found for a
           given well.
        k: Maximum growth rate. Highest slope (growth) found for given
           well.
        t0: The timepoint of k.
        A0: Initial population size (called N_0 in Gompertz)
        nu: Shape parameter.
    """
    Q = ((A / A0) ** nu) - 1
    return A * (1 + Q * np.exp(-k * (t - t0))) ** (-1 / nu)
```

**Comment by gevhaz** [comment]
Do these values look right for Richard's?

```
                   A1          A2          A3
N_0_opt      4.511152    4.039607    0.521351
N_inf_opt    1.397241    1.003642    1.265099
alpha_opt    0.031169    0.025867    0.028663
R_2         -0.342961    0.692161    0.246159
RMSE         0.333926    0.269367    0.350626
AIC        409.544346  347.239336  423.695969
```
